= Brainstorm

== Goal
_To Create a minimalistic service and client for a graph-based information storage
system which concentrates on the dynamic complexity of information systems._

Brainstorm is built from "topics," "facts,", and "documents." Topics are names
to which a user can attach facts. Facts are descriptive information attached to
and shared by one or more facts; they are used to describe on a topic or relate
topics to one another. Documents are the bodies of knowledge that emerge from
the description and association of topics. As topics are added to the system,
more documents come into existance. As facts are added to and between topics,
documents grow dynamically to reflect that new information.

Facts are shared between topics naturally, limiting redundant data entry,
expressing the relationships between ideas, and furthermore encouraging
identification of new relationships between seemingly remote subjects
("elaboration").

== Design

=== Data Structure

Topics and facts are implemented as nodes and edges within a graph,
respectively. Topics contain a label to identify their subject, and facts
contain textual content to describe whatever facts they relate. Documents are
rooted trees; they are dynamically generated by querying the graph for a
particular topic and its facts. Note therefore that if a fact relates two
topics, the content of that fact is shared by the document generated from either
topic.

=== Database

A Neo4j server manages the graph of topics and facts.

=== Client

A ruby CLI client consumes instructions from the user and issues HTTP requests
to the service. Any complex input is handled by invoking an arbitrary
text-editor process such as `vim` or `gedit`.

=== Service

An Elixir REST server consumes HTTP requests and translates those to Neo4j
queries. The REST server and database access logic are handled by two
independent Elxir applications.

==== Endpoints

[options=header]
|===
| Route                           | Action             | Normal Responses
| `POST   /topic`                 | <<Create Topic>>   | 201, 400
| `PUT    /topic/:id`             | <<Update Topic>>   | 204, 400, 404
| `DELETE /topic/:id`             | <<Delete Topic>>   | 204, 404, 409
| `GET    /topic?search=<search>` | <<Find Topic>>     | 200, 400, 404
| `GET    /document/:id`          | <<Fetch Document>> | 200, 404
| `POST   /fact`                  | <<Create Fact>>    | 201, 400
| `PUT    /fact/:id`              | <<Update Fact>>    | 204, 400, 404
| `DELETE /fact/:id`              | <<Delete Fact>>    | 204, 404
|===

===== Create Topic
_POST /topic_

Create a new topic. A request must contain an application/json header and a JSON
body in the following format:

----
{
  "label": <label>
}
----

The "label" field cannot be empty.

* `201`: The topic was created. The response body contains the id of the new
topic:
+
----
<id>
----

* `400`: The request body is invalid.

===== Update Topic
_PUT /topic/:id_

Overwrite the label of an existing topic. The request must contain an
application/json header and a JSON body in the following format:

----
{
  "label": <label>
}
----

The "label" field cannot be empty.

* `204`: The topic was successfully updated.
* `400`: The request body is invalid.
* `404`: No topic with the given id exists.

===== Delete Topic
_DELETE /topic/:id_

Delete an existing topic.

* `204`: The topic and any associated facts were deleted.
* `404`: No topic with the given id exists.

===== Find Topic
_GET /topic?search=<search>_

Find topics that match a given search term.

* `200`: Zero or more topics match the given search term. The response body
contains a JSON list of those topics:
+
----
[
  { "id": <id>, "label": <label> },
  ...
]
----

* `400`: The request is missing a search parameter.

===== Fetch Document
_GET /document/:id_

Fetch a dynamically-generated document from the given topic id.

* `200`: The topic and its associated facts were found. The response body
contains JSON in the following format, indicating the topic and its facts:
+
----
{
  "topic": { "id": <id>, "label": <label> },
  "facts": [
    {
      "id": <id>,
      "content": <content>,
      "topics": [
        { "id": <id>, "label": <label> },
        ...
      ]
    },
    ...
  ]
}
----
+
The "topic" is the root topic used to generate the document. The "facts" field
lists every fact associated with the root topic. Each fact object contains a
"topics" list of every topic with which the fact is associated.

* `404`: No topic with the given id exists.

===== Create Fact
_POST /fact_

Create a new fact associated with given a given topic or topics. The request
must contain an application/json header and a JSON body in the following format:

----
{
  "topics": [ <id | search term>, ... ],
  "content": <content>
}
----

The "topics" list must contain at least one id or search term. The "content"
field cannot be empty.

* `201`: The fact was created. The response body contains the id of the new
fact:
+
----
<id>
----

* `200`: The fact could not be created because one or more search terms could
not resolve to unique topic ids. The response body contains up to three
candidates for each such term:
+
----
{
  "search term 1": [ <topic>, ... ],
  "search term 2": [ <topic>, ... ]
  ...
}
----

* `400`: The request body is invalid.

===== Update Fact
_PUT /fact/:id_

Overwrite the content of a fact with the given id. The request must contain an
application/json header and a JSON body in the following format:

----
{
  "id": <id>,
  "topics": [ <id>, ... ]
  "content": <content>
}
----

The "topcs" list must contain at least one id. The "content" field cannot be
empty.

* `204`: The fact content was overridden.
* `400`: The request body is invalid.
* `404`: No fact with the given id exists.

===== Delete Fact
_DELETE /fact/:id_

Delete the fact with the indicated id.

* `204`: The fact was deleted.
* `404`: No fact with the given id exists.
