= Brainstorm

== Goal
_To Create a minimalistic service and client for a graph-based information storage
system which concentrates on the dynamic complexity of information systems._

This system is composed of topics and facts. Topics are names which a
client can query and to which a client may associate facts. Facts are
descriptive text associated with one or more topics. Facts are added to the
system over time, causing topics to grow dynamically. Facts are shared
between topics naturally, limiting redundant data entry, expressing the
relationships between ideas, and furthermore encouraging identification of
new relationships between seemingly remote subjects ("elaboration").

== Design

=== Data Structure

Topics are implemented as named nodes in a graph. Facts are (hyper)edges
between nodes with associated metadata. In particular, topics have a UTF-8
`label` attribute and facts have a UTF-8 `content` attribute.

Both topics and facts have a UUID `id` attribute to uniquely identify them.
This attribute is used to interact with these elements unambiguously. Facts use
id's to identify which topics they are associated with.

=== Database

A Neo4j server manages the graph of topics and facts.

=== Client

A python CLI client consumes instructions from the user and issues HTTP requests
to the service. Any complex input is handled by invoking an arbitrary
text-editor process such as `vim` or `gedit`.

=== Service

An Elixir REST server consumes HTTP requests and translates those to Neo4j
queries. The REST server and database access logic are handled by two
independent Elxir applications.

==== Endpoints

[options=header]
|===
| Route                           | Action           | Normal Responses
| `POST   /topic`                 | <<Create Topic>> | 201, 400
| `PUT    /topic/:id`             | <<Update Topic>> | 204, 400, 404
| `DELETE /topic/:id`             | <<Delete Topic>> | 204, 404, 409
| `GET    /topic?search=<search>` | <<Find Topic>>   | 200, 400, 404
| `GET    /topic/:id`             | <<Query Topic>>  | 200, 404
| `POST   /fact`                  | <<Create Fact>>  | 201, 400
| `PUT    /fact/:id`              | <<Update Fact>>  | 204, 400, 404
| `DELETE /fact/:id`              | <<Delete Fact>>  | 204, 404
|===

===== Create Topic
_POST /topic_

Create a new topic. A request must contain an application/json header and a JSON
body in the following format:

----
{
  "label": <label>
}
----

The "label" field cannot be empty.

* `201`: The topic was created. The response body contains the id of the new
topic:
+
----
<id>
----

* `400`: The request body is invalid.

===== Update Topic
_PUT /topic/:id_

Overwrite the label of an existing topic. The request must contain an
application/json header and a JSON body in the following format:

----
{
  "label": <label>
}
----

The "label" field cannot be empty.

* `204`: The topic was successfully updated.
* `400`: The request body is invalid.
* `404`: No topic with the given id exists.

===== Delete Topic
_DELETE /topic/:id_

Delete an existing topic.

* `204`: The topic was deleted.
* `404`: No topic with the given id exists.
* `409`: One or more facts are associated with the topic, which must be deleted
first before the topic can be removed. The response body contains a json list of
those facts' ids.
+
----
[
  <id>,
  ...
]
----

===== Find Topic
_GET /topic?search=<search>_

Find topics that match a given search term.

* `200`: One or more topics match the given search term. The response body
contains a JSON list of those topics:
+
----
[
  { "id": <id>, "label": <label> },
  ...
]
----

* `400`: The request is missing a search parameter.
* `404`: No topic matches the search term.

===== Query Topic
_GET /topic/:id_

Fetch a topic and its associated facts.

* `200`: The topic and its associated facts were found. The response body
contains JSON in the following format, indicating the topic and its facts:
+
----
{
  "label": <label>,
  "facts": [
    {
      "topics": [
        { "id": <id>, "label": <label> },
        ...
      ],
      "content": <content>
    },
    ...
  ]
}
----
+
The "facts" field lists every fact associated with the queried topic. Each
fact object contains a "topics" list of every topic with which the fact is
associated except for the queried topic itself.

* `404`: No topic with the given id exists.

===== Create Fact
_POST /fact_

Create a new fact associated with given a given topic or topics. The request
must contain an application/json header and a JSON body in the following format:

----
{
  "topics": [ <id>, ... ],
  "content": <content>
}
----

The "topics" list must contain at least one id. The "content" field cannot be
empty.

* `201`: The fact was created. The response body contains the id of the new
fact:
+
----
<id>
----

* `400`: The request body is invalid.

===== Update Fact
_PUT /fact/:id_

Overwrite the content of a fact with the given id. The request must contain an
application/json header and a JSON body in the following format:

----
{
  "id": <id>,
  "topics": [ <id>, ... ]
  "content": <content>
}
----

The "topcs" list must contain at least one id. The "content" field cannot be
empty.

* `204`: The fact content was overridden.
* `400`: The request body is invalid.
* `404`: No fact with the given id exists.

===== Delete Fact
_DELETE /fact/:id_

Delete the fact with the indicated id.

* `204`: The fact was deleted.
* `404`: No fact with the given id exists.
