require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "unit-tests"
  t.libs << "lib"
  t.test_files = FileList["unit-tests/**/*.spec.rb"]
end

task :default => :test
